apiVersion: v1
kind: ConfigMap
metadata:
  name: webshop-config
data:
  environment: "production"
  log_level: "info"
  auth_service_url: "http://prod-auth-service:8081"
  product_service_url: "http://prod-product-service:8082"
  checkout_service_url: "http://prod-checkout-service:8083"