apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: webshop-prod

namespace: webshop-prod

resources:
  - ../../base
  - namespace.yaml

namePrefix: prod-

commonLabels:
  environment: prod

patchesStrategicMerge:
  - replica-patch.yaml
  - resource-patch.yaml

images:
  - name: hosseicyber/webshop-auth
    newTag: "1.0.0"
  - name: hosseicyber/webshop-product  
    newTag: "1.0.0"
  - name: hosseicyber/webshop-checkout
    newTag: "1.0.0"