apiVersion: v1
kind: ConfigMap
metadata:
  name: webshop-config
data:
  environment: "development"
  log_level: "debug"
  auth_service_url: "http://dev-auth-service:8081"
  product_service_url: "http://dev-product-service:8082"
  checkout_service_url: "http://dev-checkout-service:8083"