apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lgtm-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  sources:
    - repoURL: https://grafana.github.io/helm-charts
      chart: lgtm-distributed
      targetRevision: 3.0.1
      helm:
        releaseName: lgtm
        valueFiles:
          - $values/argocd/values/lgtm-values.yaml
    - repoURL: https://github.com/hossei-cyber/Devops_Project.git
      targetRevision: HEAD
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
