apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webshop-dev
  namespace: argocd
  labels:
    environment: dev
spec:
  project: default
  source:
    repoURL: https://github.com/hossei-cyber/Devops_Project.git
    targetRevision: HEAD
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: webshop-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
