apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./../../base
- ./configmap.yaml

namePrefix: prod-
namespace: webshop-prod

images:
- name: hosseicyber/webshop-auth
  newTag: "1.0.0"
- name: hosseicyber/webshop-product
  newTag: "1.0.0"
- name: hosseicyber/webshop-checkout
  newTag: "1.0.0"