apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service
  labels:
    app: checkout-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: checkout-service
  template:
    metadata:
      labels:
        app: checkout-service
    spec:
      containers:
      - name: checkout-service
        image: hosseicyber/webshop-checkout:1.0.0
        ports:
        - containerPort: 8083
        env:
        - name: PORT
          value: "8083"
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:8081"
        - name: PRODUCT_SERVICE_URL
          value: "http://product-service:8082"
        livenessProbe:
          httpGet:
            path: /checkout/placeorder
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /checkout/placeorder
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"