apiVersion: v1
kind: Service
metadata:
  name: checkout-service
  labels:
    app: checkout-service
spec:
  selector:
    app: checkout-service
  ports:
  - name: http
    port: 8083
    targetPort: 8083
    protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-service-nodeport
  labels:
    app: checkout-service
spec:
  selector:
    app: checkout-service
  ports:
  - name: http
    port: 8083
    targetPort: 8083
    nodePort: 30083
    protocol: TCP
  type: NodePort